import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import {LineChart,Line,BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer} from "recharts";
import "./style.css";
const API="http://localhost:8000";
const text={en:{dash:"Dashboard",pred:"Energy Prediction",machines:"Machine Efficiency",history:"Energy History",insights:"AI Insights",upload:"Upload Data",title:"Smarter Energy Management for Doubling Mills",sub:"Predict energy consumption, monitor machine efficiency, identify abnormal usage, and make data-driven decisions with AI.",launch:"Launch Dashboard",dataset:"Synthetic / Demo Dataset Active",total:"Total Machines",today:"Today's Energy",pe:"Predicted Energy",eff:"Average Efficiency",high:"High Consumption Machines",prod:"Today's Production",inputs:"Prediction Inputs",button:"PREDICT ENERGY"},ta:{dash:"டாஷ்போர்டு",pred:"ஆற்றல் கணிப்பு",machines:"இயந்திர திறன்",history:"ஆற்றல் வரலாறு",insights:"AI நுண்ணறிவு",upload:"தரவு பதிவேற்றம்",title:"டப்ளிங் மில்களுக்கான புத்திசாலி ஆற்றல் மேலாண்மை",sub:"AI மூலம் மின்சார பயன்பாட்டை கணித்து, இயந்திர திறனை கண்காணித்து, அதிக பயன்பாட்டை கண்டறியுங்கள்.",launch:"டாஷ்போர்டை திறக்கவும்",dataset:"செயற்கை / டெமோ தரவு செயல்பாட்டில்",total:"மொத்த இயந்திரங்கள்",today:"இன்றைய ஆற்றல்",pe:"கணிக்கப்பட்ட ஆற்றல்",eff:"சராசரி திறன்",high:"அதிக பயன்பாட்டு இயந்திரங்கள்",prod:"இன்றைய உற்பத்தி",inputs:"கணிப்பு உள்ளீடுகள்",button:"ஆற்றலை கணிக்கவும்"}};
function App(){const[lang,setLang]=useState("en"),[page,setPage]=useState("dash"),[d,setD]=useState(),[ms,setMs]=useState([]),[h,setH]=useState([]),[r,setR]=useState(null);
const[f,setF]=useState({machine_id:"M04",date:"2026-09-15",shift:"Morning",operating_hours:10,expected_production:350,previous_energy:88,downtime:1,maintenance_count:2,machine_age:5});const T=text[lang];
useEffect(()=>{fetch(API+"/api/dashboard").then(x=>x.json()).then(setD);fetch(API+"/api/machines").then(x=>x.json()).then(setMs);fetch(API+"/api/history").then(x=>x.json()).then(setH)},[]);
async function predict(){let x=await fetch(API+"/api/predict",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...f,operating_hours:+f.operating_hours,expected_production:+f.expected_production,previous_energy:+f.previous_energy,downtime:+f.downtime,maintenance_count:+f.maintenance_count,machine_age:+f.machine_age})});setR(await x.json())}
if(!d)return <div className="load">Loading DoublingIQ...</div>;
return <div className="app"><aside><div className="brand">⚡ <b>DoublingIQ</b></div><div className="tag">TEXTILE ENERGY INTELLIGENCE</div><div className="demo">● {T.dataset}</div>{[["dash",T.dash],["pred",T.pred],["machines",T.machines],["history",T.history],["insights",T.insights],["upload",T.upload]].map(x=><button className={page==x[0]?"nav on":"nav"} onClick={()=>setPage(x[0])}>{x[1]}</button>)}</aside>
<main><header><span>TEXTILE DOUBLING MILL</span><button onClick={()=>setLang(lang==="en"?"ta":"en")}>🌐 {lang==="en"?"தமிழ்":"English"}</button></header>
{page==="dash"&&<><div className="hero"><span className="pill">✨ Textile Doubling Mill AI Suite</span><h1>{T.title}</h1><p>{T.sub}</p><button className="primary" onClick={()=>setPage("pred")}>{T.launch} →</button></div><h2>{T.dash}</h2><div className="cards">{[[T.total,d.total_machines],[T.today,d.today_energy+" kWh"],[T.pe,d.predicted_energy+" kWh"],[T.eff,d.average_efficiency+" kWh/kg"],[T.high,d.high_consumption_machines],[T.prod,d.today_production+" kg"]].map(x=><div className="card"><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><div className="charts"><div className="panel"><h3>Energy Consumption Trend</h3><ResponsiveContainer width="100%" height={250}><LineChart data={h.slice(-20)}><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="energy_consumption_kwh"/></LineChart></ResponsiveContainer></div><div className="panel"><h3>Machine Energy Comparison</h3><ResponsiveContainer width="100%" height={250}><BarChart data={ms}><XAxis dataKey="machine_id"/><YAxis/><Tooltip/><Bar dataKey="energy"/></BarChart></ResponsiveContainer></div></div></>}
{page==="pred"&&<><h2>⚡ {T.pred}</h2><div className="panel"><h3>{T.inputs}</h3><div className="form">{Object.entries({machine_id:"Machine ID",shift:"Shift",operating_hours:"Operating Hours",expected_production:"Expected Production (kg)",previous_energy:"Previous Energy (kWh)",downtime:"Downtime (hours)",maintenance_count:"Maintenance Count",machine_age:"Machine Age"}).map(([k,l])=><label>{l}<input value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}</div><button className="primary" onClick={predict}>🔮 {T.button}</button></div>{r&&<div className="result"><span className="pill">🤖 AI ENERGY PREDICTION</span><h1>{r.predicted_kwh} kWh</h1><p>Expected Range: {r.range[0]} – {r.range[1]} kWh</p><p>Efficiency: {r.efficiency} kWh/kg</p><b>🟢 {r.status}</b><small>{r.dataset}</small></div></>}
</>}
{page==="machines"&&<Table title={T.machines} rows={ms.map(x=>[x.machine_id,x.energy+" kWh",x.production+" kg",x.efficiency+" kWh/kg"])} heads={["Machine","Energy","Production","Efficiency"]}/>}
{page==="history"&&<Table title={T.history} rows={h.slice(-25).reverse().map(x=>[x.date,x.machine_id,x.shift,x.production_quantity+" kg",x.energy_consumption_kwh+" kWh",(x.energy_consumption_kwh/x.production_quantity).toFixed(3)])} heads={["Date","Machine","Shift","Production","Energy","Efficiency"]}/>}
{page==="insights"&&<Info title={"🤖 "+T.insights} text="Review machines with persistently higher energy per kg and compare production alongside energy. Insights should be based on stored data; this demo uses synthetic data."/>}
{page==="upload"&&<Info title={T.upload} text="CSV columns: machine_id, date, shift, operating_hours, production_quantity, energy_consumption_kwh, downtime_hours, maintenance_count, machine_age."/>}</main></div>}
function Table({title,rows,heads}){return <section><h2>{title}</h2><div className="panel"><table><thead><tr>{heads.map(x=><th>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr>{r.map(x=><td>{x}</td>)}</tr>)}</tbody></table></div></section>}
function Info(p){return <section><h2>{p.title}</h2><div className="panel"><p>{p.text}</p></div></section>}
createRoot(document.getElementById("root")).render(<App/>);